# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product-Hunt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Moya'
  
  # Kingfisher is a lightweight library for downloading and caching images from the web.
  pod 'Kingfisher', '~> 4.0'

  # Pods for Product-Hunt

end
